### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by chumleyex** [fireshaper/Omnibus#1]
No matter where I try this from I get this error.. If I go to the IP listed via https I get this msg. I do an nslookup for getcomics.info and I get that ip and 10.112, but those still don't work in my browser.. Any idea what's going on here? the url works fine. I'm trying from 3 different networks. I'm on the newest version.

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

(07-25-19 22:07:19) - Searching for https://getcomics.info/page/1/?s= failed.
(07-25-19 22:07:19) - System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time or established connection failed because connected host has failed to respond 104.28.11.112:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Omnibus.Form1.searchComics(String function)

**Comment by chumleyex** [comment]
I redownloaded 1.4.2.0 and get this.

(07-26-19 14:37:51) - Searching for https://getcomics.info/page/1/?s= failed.
(07-26-19 14:37:51) - System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time or established connection failed because connected host has failed to respond 104.28.10.112:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Omnibus.Form1.searchComics(String function)
(07-26-19 14:38:37) - Searching for https://getcomics.info/page/1/?s= failed.
(07-26-19 14:38:37) - System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time or established connection failed because connected host has failed to respond 104.28.10.112:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Omnibus.Form1.searchComics(String function)
